/**
 * Branded PDF export for diary summaries.
 */

function downloadSummaryPdf_(profile) {
  var summary = getSummary_(profile);
  var org = String((profile && (profile.organisation || profile.company)) || getCompany_() || 'Daily Diary').trim();
  var displayName = String((profile && profile.name) || 'Intern').trim();
  var username = String((profile && profile.username) || '').trim();
  var today = todayNairobi_();
  var doc = DocumentApp.create('Daily Diary Summary — ' + displayName + ' — temp');
  var body = doc.getBody();
  body.clear();

  var title = body.appendParagraph(org);
  title.setHeading(DocumentApp.ParagraphHeading.HEADING1);
  title.setForegroundColor('#0B3D2E');
  title.setBold(true);
  title.setAlignment(DocumentApp.HorizontalAlignment.CENTER);

  var subtitle = body.appendParagraph('Internship Daily Diary — Summary Report');
  subtitle.setHeading(DocumentApp.ParagraphHeading.HEADING2);
  subtitle.setForegroundColor('#1B5E45');
  subtitle.setAlignment(DocumentApp.HorizontalAlignment.CENTER);

  body.appendParagraph('');
  appendPdfMetaLine_(body, 'Intern', displayName);
  if (username) {
    appendPdfMetaLine_(body, 'Username', '@' + username);
  }
  appendPdfMetaLine_(body, 'Generated', today);
  appendPdfMetaLine_(body, 'Days logged', String((summary.totals && summary.totals.daysLogged) || 0));
  appendPdfMetaLine_(body, 'Total hours', String((summary.totals && summary.totals.totalHours) || '0.00'));
  appendPdfMetaLine_(body, 'Open tasks', String((summary.totals && summary.totals.tasksOpen) || 0));
  appendPdfMetaLine_(body, 'Urgent tasks', String((summary.totals && summary.totals.tasksUrgent) || 0));
  appendPdfMetaLine_(body, 'Overdue tasks', String((summary.totals && summary.totals.tasksOverdue) || 0));

  var weeks = summary.weeks || [];
  if (!weeks.length) {
    body.appendParagraph('');
    body.appendParagraph('No diary weeks logged yet.').setItalic(true);
  }

  weeks.forEach(function (week) {
    body.appendParagraph('');
    var weekHead = body.appendParagraph(
      'Week ' + week.weekNumber + '  ·  ' + week.rangeShort +
      '  ·  ' + week.daysLogged + ' days  ·  ' + week.totalHours + ' hrs'
    );
    weekHead.setHeading(DocumentApp.ParagraphHeading.HEADING3);
    weekHead.setForegroundColor('#0B3D2E');
    weekHead.setBold(true);

    var tableData = [['Day', 'Date', 'In', 'Out', 'Hours', 'Assignment']];
    (week.days || []).forEach(function (day) {
      if (!day.saved) {
        return;
      }
      tableData.push([
        String(day.weekday || ''),
        String(day.date || ''),
        String(day.timeIn || ''),
        String(day.timeOut || ''),
        String(day.hoursWorked != null ? day.hoursWorked : ''),
        truncatePdfText_(String(day.assignment || '').replace(/\r\n/g, '\n'), 500)
      ]);
    });

    if (tableData.length === 1) {
      body.appendParagraph('No days logged this week.').setItalic(true);
      return;
    }

    var table = body.appendTable(tableData);
    table.setBorderColor('#1B5E45');
    table.setBorderWidth(0.5);
    var headerRow = table.getRow(0);
    for (var c = 0; c < headerRow.getNumCells(); c++) {
      var cell = headerRow.getCell(c);
      cell.setBackgroundColor('#0B3D2E');
      var text = cell.editAsText();
      text.setForegroundColor('#FFFFFF');
      text.setBold(true);
    }
  });

  body.appendParagraph('');
  var footer = body.appendParagraph('Generated by Daily Diary');
  footer.setForegroundColor('#5A7A6E');
  footer.setFontSize(9);
  footer.setAlignment(DocumentApp.HorizontalAlignment.CENTER);

  doc.saveAndClose();
  var file = DriveApp.getFileById(doc.getId());
  var blob = file.getAs(MimeType.PDF);
  var base64 = Utilities.base64Encode(blob.getBytes());
  try {
    file.setTrashed(true);
  } catch (err) {
    // Best-effort cleanup; PDF bytes already captured.
  }

  return {
    ok: true,
    filename: 'Daily-Diary-Summary-' + today + '.pdf',
    mimeType: 'application/pdf',
    base64: base64
  };
}

function appendPdfMetaLine_(body, label, value) {
  var paragraph = body.appendParagraph(label + ': ' + value);
  paragraph.setForegroundColor('#16382C');
  paragraph.setSpacingAfter(2);
}

function truncatePdfText_(text, maxLen) {
  var value = String(text || '');
  if (value.length <= maxLen) {
    return value;
  }
  return value.slice(0, maxLen - 1) + '…';
}
